### ISSUE TITLE
Project title: Broadcasting spells or How to broadcast

### ISSUE THREAD

**Issue by megwangrpf** [raspberrypilearning/broadcasting-spells#14]
Since we're meant to avoid gerunds, I've suggested changing the project title to 'How to broadcast spells'. However, this would effect the project title here and on the Scratch site. So let me know what you prefer and I can make sure it's consistent across the steps. Thanks!

**Comment by libxx1** [comment]
Hi @megwangrpf , we had a chat about it at the team meeting this morning and would really like to keep it as 'Broadcasting spells' is that ok? I know it's not completely ideal but none of the alternatives are without issue (either because of language constraints or in keeping it an exciting project for an informal club). Nina is going to add a note for translators when they are working on this project so they know both the Scratch block & magic links behind the choice of title.

**Comment by megwangrpf** [comment]
Thanks @libxx1! You and the translation team are the experts. Glad 'Broadcasting spells' will work!
